name: Flutter Firebase Deploy

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    env:
      SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
      SUPABASE_ANNON_KEY: ${{ secrets.SUPABASE_ANNON_KEY }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Flutter
        uses: subosito/flutter-action@v1

      - name: Install Dependencies
        run: flutter pub get

      - name: Build Web
        run: flutter build web

      - name: Deploy to Firebase
        uses: w9jds/firebase-action@v1
        with:
          args: deploy --only hosting

      - name: Cleanup
        run: rm -rf .firebase


